### ISSUE TITLE
[Feature] Weapon switching speed

### ISSUE THREAD

**Issue by NightFright2k19** [Russian-Doom/russian-doom#305] opened 2022-02-01 10:02 UTC
It would be great to have an option which allows to increase the speed of switching weapons (2x faster should be enough). There are mods for GZDoom which work via DECORATE or ZScript that can do this and it helps especially in slaughter maps where fast weapon switching can make a difference.

Possible problem: 
I don't know if this can be implemented as a general feature which would work for ANY weapon, even if modified.

**Comment by JNechaevsky** [comment] 2022-02-02 08:55
I'm afraid having such micro-switch is something both uncanonical and unconventional in terms of game mechanics. There are already some bug fixes and improvements that's making mechanics no longer 100% identical to vanilla, but they aren't much notable and aren't applying while demo recording/playing, mostly to provide compatibility with IWAD demos.

However, faster switching is possible via pure Dehacked. A notable example is Doomkid's [Rowdy Rudy II: POWERTRIP](https://doomwiki.org/wiki/Rowdy_Rudy_II:_POWERTRIP). It works fine in RD except small problem: "double" visual effect while weapon switching. It is caused by applying weapon bobbing while firing/lowering/raise states (can be fixed by turning off "Weapon bobbing while firing" in "Gameplay / Physical"), and there is nothing a can do about it - after couple of attempts, this is as far as I can go with compatibility. :(

 Sadly, yes, increasing of raise/lower states will not affect all possible mods.

**Comment by NightFright2k19** [comment] 2022-02-02 09:58
Ah well, I thought there was maybe an easy way like tell the engine to skip every 2nd frame during the weapon raising state or something. If it's out of scope for this project, it's not a problem for me. Similar case as the smooth weapon animations which are also available in DEHACKED (vsmooth.wad). They work with any PWAD that doesn't modify weapons.

Just wondered whether it was something that could be done by coding magic.

**Closed as completed** 2022-02-02 10:00 UTC
Labels: enhancement

**Comment by JNechaevsky** [comment] 2022-02-02 21:14
Technically, with code at hand everything is possible. :)

But have a look at playthroughs of notable players like decino and Zero Master, how they are playing famous slaughter maps Sunder or Okuplok (recordings on YouTube). They aren't using free look and etc., and playing strictly on PrBoom+ which is a paragon of vanilla gameplay, with all it's bugs, quirks and tricks. I mean, faster weapon switching is more a cheat than aide, unless the mod itself is supposed to have it. 

Despite of RD is no longer 100% vanilla identical, I'm trying to preserve vanilla "feeling" and never, never don't turn it into a mod. It's a very unusual way, because from one side I want to make things better, and from another I have to care about IWAD demos and overall _"this is still Doom and should be felt like Doom, and not a "he-ey, I've made everything what I could better than in was in 1994 and it's all from the box!""_.

**Comment by NightFright2k19** [comment] 2022-02-02 22:04
I guess I have just been using GZDoom for too long. Mods are a big thing there, as you know. In RD, with all its enhancements compared to Choco/Crispy Doom, I tend to forget it's still about preserving that vanilla gameplay and some mods I am used to activate in GZD just won't fly here.

I admit it's a trap I often fall for: Finding a cool new port which has all these nice features, but missing some of those I like so much in another... and then trying to get it turned into some kinda hybrid. I should really stop with that.

But hey, that really cool system clock option you got there? GZDoom still doesn't have it and I've been waiting for it since years! And here it's a menu option. Just like that.
