### ISSUE TITLE
[BUG] Bullets not being registered properly

### ISSUE THREAD

**Issue by nesper8** [Russian-Doom/russian-doom#384] opened 2022-09-24 04:37 UTC
### International Doom version

International Doom 6.0

### What Operating System are you using?

Linux

### What Build variant of International Doom are you using?

x64 (x86_64, win64, amd64)

### Please describe your specific OS version

Nobara 36; nobara 5.19.9-201.fsync.fc36.x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

[output.webm](https://user-images.githubusercontent.com/57890520/192079951-e6f17790-3a39-4c76-a09d-76da6e755518.webm)

**Comment by JNechaevsky** [comment] 2022-09-24 05:50
Confirmed, thanks. Looks likes bullet tracers are broken if "Strict vanilla mode" in Gameplay Features is set to "off".

**Comment by JNechaevsky** [comment] 2022-09-24 06:18
Fixed in https://github.com/JNechaevsky/inter-doom/commit/a08bcc2310a500201080f8e0b93edab74cf7c924. Looks likes by caring too much about "strict mode" I totally forgot to check how things are going in non-strict, casual mode. This definitely worth a small point-release, because having broken hitscan weapons is a catastrophe.

**Closed as completed by JNechaevsky** 2022-09-24 06:18 UTC
Labels: bug

**Comment by nesper8** [comment] 2022-09-24 06:25
ayy thank you very much for the quick fix
