### ISSUE TITLE
[BUG] Analog sticks sensivity with XBOX360 pad

### ISSUE THREAD

**Issue by vanfanel** [Russian-Doom/russian-doom#346] opened 2022-05-21 10:34 UTC
### International Doom version

International Doom 5.2.1

### What Operating System are you using?

Linux

### What Build variant of International Doom are you using?

x64 (amd64, x86_64, win64)

### If Other OS or Build variant, please describe

Debian

### Relevant hardware info

AMD

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Hi!

I noticed that, when using an XBOX360 gamepad, analog stick sensitivity is way toom high.
Even setting sensitivity to 1 on the "gamepad settings", game moves/turns way too fast to be remotely playable.

Any idea on what is going on? Maybe it's a known issue? 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start the game
2. Try to use an XBOX360-compatible gamepad
3. Try to play using the analog sticks

### Your configuration

https://gist.github.com/vanfanel/39ae3f3f9f9d72956194b275c729dd95

**Comment by Dasperal** [comment] 2022-05-21 11:47
There was a bug with axis input scaling in Heretic and Hexen fixed in 79e1696f01b5828c37acc644ffbfb26156998b0a

In Doom i can't reproduce this problem. At least on Windows

**Comment by vanfanel** [comment] 2022-05-21 12:55
@Dasperal Thanks, I can see a great improvement with current GIT code.

However, sensitivity is still too high on the "Left x axis" and "Left y axis".
In fact, I can see no difference bewteen sensitivity set to 1 or 16.

Right axis work perfectly and their sensitivity setting seems to be applied correctly: it's only the left ones that seem to ignore the sensitivity setting.

**Comment by Dasperal** [comment] 2022-05-21 13:30
Ow. Looks like I missed scaling of `joymove` and `joystrafemove` too.

**Closed as completed** 2022-05-23 09:34 UTC
Labels: bug

**Comment by vanfanel** [comment] 2022-05-23 10:22
@Dasperal thanks! Works perfectly. now
